server:
  port: 8088
  servlet:
    context-path: /feedback
spring:
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:kafka}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: review-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/review_db?authSource=admin}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 60000
            read-timeout: 120000
          file-service:
            url: ${FEIGN_FILE:http://file-service:8084/file}
            connect-timeout: 30000
            read-timeout: 60000