server:
  port: 8088
spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:root@mongodb:27017/review_db?authSource=admin}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 60000
            read-timeout: 120000
          file-service:
            url: ${FEIGN_FILE:http://file-service:8084/file}
            connect-timeout: 30000
            read-timeout: 60000